_wandb:
    value:
        cli_version: 0.19.7
        m: []
        python_version: 3.10.11
        t:
            "1":
                - 1
                - 5
                - 53
                - 55
            "2":
                - 1
                - 5
                - 53
                - 55
            "3":
                - 2
                - 16
                - 23
                - 55
            "4": 3.10.11
            "5": 0.19.7
            "8":
                - 1
                - 3
                - 5
            "12": 0.19.7
            "13": windows-amd64
architecture:
    value: simpleff
epochs:
    value: 3
